[tool.black]
line-length = 110
skip-numeric-underscore-normalization = true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | static
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = 'app'
known_third_party = [
    "aiofiles",
    "fastapi",
    "pytest",
    "requests",
    "starlette"
]
line_length = 110
multi_line_output = 3
skip_glob = ''
use_parentheses = true
combine_as_imports = true

sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'

[tool.pytest.ini_options]
addopts = "--failed-first --tb=short --verbosity=2 --cov=app --cov-report=term-missing"
filterwarnings = [
    "ignore:.*is deprecated.*:DeprecationWarning",
    "ignore:.*using non-Enum.*:DeprecationWarning",
    "ignore::UserWarning",
]

[tool.coverage.run]
# Do not create coverage for test files, as they are always 100%
omit = ["tests/**"]
